server: 
   port: 8761
eureka: 
   client: 
      registerWithEureka: false   # 表示是否将自己注册到eureka中，默认为true
      fetchRegistry: false    # 表示是否从eureka中获取注册信息，默认为true
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/   # 表示设置与Eureka交互的地址，默认为localhost:8761/eureka/